[project]
name = "engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tarunbtw", email = "tharun30115@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "groq>=1.7.0",
    "joblib>=1.6.0",
    "pandas>=3.0.5",
    "pdfplumber>=0.11.10",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
engine = "engine:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
